TEAM_HUMAN = 'TEAM_HUMAN'
TEAM_WOLF = 'TEAM_WOLF'

CHAR_WOLF = 'WOLF'
CHAR_SEER = 'SEER'
CHAR_VILLAGER = 'VILLAGER'
CHAR_GUARD = 'GUARD'
CHAR_WITCH = 'WITCH'

MISC_WOLFPACK = 'WOLFPACK'

ACTION_PROTECT = 'PROTECT'
ACTION_KILL = 'KILL'
ACTION_REVIVE = 'REVIVE'